/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMT;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author arturohdez
 */
public class Hoyno extends javax.swing.JFrame {

    /**
     * Creates new form Hoyno
     */
    
    HoyNoC n ;
    
    
    
    public Hoyno() {
        n = new HoYNoC();
        initComponents();
        cb1.removeAllItems();
        cb1.addItem("1");
        cb1.addItem("2");
        cb1.addItem("3");
        cb1.addItem("4");
        cb1.addItem("5");
        cb1.addItem("6");
        cb1.addItem("7");
        cb1.addItem("8");
        cb1.addItem("9");
        cb1.addItem("0");
        cb1.addItem("");
        
        cb2.removeAllItems();
        cb2.addItem("lunes");
        cb2.addItem("martes");
        cb2.addItem("miercoles");
        cb2.addItem("jueves");
        cb2.addItem("viernes");
        cb2.addItem("");
        
        cb3.removeAllItems();
        cb3.addItem("amarillo");
        cb3.addItem("rosa");
        cb3.addItem("rojo");
        cb3.addItem("verde");
        cb3.addItem("azul");
        cb3.addItem("");
        
        b1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) 
            {
                String s = cb1.getSelectedItem()
            }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt4 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        cb3 = new javax.swing.JComboBox();
        cb1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt4.setText("jTextField4");
        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });

        b1.setText("jButton1");

        b2.setText("jButton2");

        jLabel1.setText("Placa");

        jLabel2.setText("Día");

        jLabel3.setText("Color");

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(jLabel1)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoyno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoyno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoyno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoyno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoyno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt4;
    // End of variables declaration//GEN-END:variables



*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMT;

/**
 *
 * @author arturohdez
 */
public class HoyNoC implements IHoyno 
{

    @Override
    
    public String HoyNoCircula() 
    {
        
        
           String jueves ="Hoy no circulan los vehículos con engomado color verde y terminación 1 y 2";
           return jueves;
    }

    @Override
    public String Placa(String t) 
    {
       if(t=="1"||t=="2")
        {
            return "jueves";
        }
       if(t=="3"||t=="4")
       {
           return "miercoles";
       }
       if(t=="5"||t=="6")
       {
           return "lunes";
       }
       if(t=="7"||t=="8")
       {
           return "martes";
       }
       if(t=="9"||t=="0")
       {
           return "viernes";
       }
        return null;
    }

    @Override
    public String TerminacionPlaca(String t) 
    {
        if(t=="jueves")
        {
            return "1,2";
        }
        if(t=="miercoles")
        {
            return "3,4";
        }
        if(t=="lunes")
        {
            return "5,6";
        }
        if(t=="martes")
        {
            return "7,8";
        }
        if (t=="viernes")
        {
            return "9,0";
        }
        return null;
        
    }

    @Override
    public String Color(String t) 
    {
        if(t=="verde")
        {
            return "jueves";
        }
        if(t=="azul")
        {
            return "viernes";
        }
        if(t=="amarillo")
        {
            return "lunes";
        }
        if(t=="rosa")
        {
            return "martes";
        }
        if(t=="rojo")
        {
            return "miercoles";
        }
        return null;
        



    }
    
}

}

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMT;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Oscar Torres
 */
public class HoyNoCirculaGraf extends javax.swing.JFrame {

    /**
     * Creates new form HoyNoCirculaGraf
     */
    public HoyNoCirculaGraf() {
        initComponents();
        cbplaca.removeAllItems();
        cbdia.removeAllItems();
        cbcolor.removeAllItems();
        cbplaca.addItem("0");
         cbplaca.addItem("1");
          cbplaca.addItem("2");
           cbplaca.addItem("3");
            cbplaca.addItem("4");
             cbplaca.addItem("5");
              cbplaca.addItem("6");
               cbplaca.addItem("7");
                cbplaca.addItem("8");
                 cbplaca.addItem("9");
                 cbcolor.addItem("amarillo");
                 cbcolor.addItem("rosa");
                 cbcolor.addItem("rojo");
                 cbcolor.addItem("verde");
                 cbcolor.addItem("azul");
                 cbdia.addItem("lunes");
                 cbdia.addItem("martes");
                 cbdia.addItem("miercoles");
                 cbdia.addItem("jueves");
                 cbdia.addItem("viernes");
                 cbdia.addItem(" ");
                 cbcolor.addItem(" ");
                 cbplaca.addItem(" ");
                 
                 revisar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String u1 =(String) cbplaca.getSelectedItem();
                String u2 =(String) cbcolor.getSelectedItem();
                String u3 =(String) cbdia.getSelectedItem();
                NoCircula NC = new NoCircula();
                if(u1== " " &&  u2== " " && u3!= " ")
                {
                  String imp = NC.getTerminacion(u3);
                  imprimirtxt.setText(imp);
                   
                }
                if(u1== " " &&  u2!= " " && u3== " "){
                    String imp = NC.getColor(u2);
                  imprimirtxt.setText(imp);
                   
                }
                if(u1!= " " &&  u2== " " && u3== " "){
                    String imp = NC.getByPlaca(u1);
                  imprimirtxt.setText(imp);
                }
                         
                
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbplaca = new javax.swing.JComboBox<>();
        cbdia = new javax.swing.JComboBox<>();
        cbcolor = new javax.swing.JComboBox<>();
        imprimirtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        revisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbplaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        imprimirtxt.setText("jTextField1");

        jButton1.setText("jButton1");

        revisar.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbplaca, 0, 146, Short.MAX_VALUE)
                    .addComponent(cbdia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbcolor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imprimirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(revisar)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprimirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(revisar))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoyNoCirculaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoyNoCirculaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoyNoCirculaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoyNoCirculaGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoyNoCirculaGraf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcolor;
    private javax.swing.JComboBox<String> cbdia;
    private javax.swing.JComboBox<String> cbplaca;
    private javax.swing.JTextField imprimirtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton revisar;
    // End of variables declaration//GEN-END:variables
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMT;

/**
 *
 * @author arturohdez
 */
public interface IHoyno 
{
    public String HoyNoCircula ();
    public String Placa (String t);
    public String TerminacionPlaca (String t);
    public String Color (String t);
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMT;

/**
 *
 * @author Oscar Torres
 */
public interface INoCircula {
    
    void getHoyNoCircula();
    String getByPlaca(String dp );
    String getTerminacion(String t);
    String getColor(String col);
    
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EMT;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Oscar Torres
 */
public class NoCircula implements INoCircula{
    String placa;
    String dia;
    String color;
    Map<String,String>lista;
    Map<String,String>lista2;
     Map<String,String>lista3;
    

    public NoCircula() {
        
        lista = new HashMap<>();
        lista.put("amarillo","lunes");
        lista.put("rosa","martes");
        lista.put("rojo","miercoles");
        lista.put("verde","jueves");
        lista.put("azul","viernes");
        lista2 = new HashMap<>();
        lista2.put("5","amarillo");
        lista2.put("6","amarillo");
        lista2.put("7","rosa");
        lista2.put("8","rosa");
        lista2.put("3","rojo");
        lista2.put("4","rojo");
        lista2.put("1","verde");
        lista2.put("2","verde");
        lista2.put("9","azul");
        lista2.put("0","azul");
         lista3 = new HashMap<>();
        lista3.put("5","lunes");
        lista3.put("6","lunes");
        lista3.put("7","martes");
        lista3.put("8","martes");
        lista3.put("3","miercoles");
        lista3.put("4","miercoles");
        lista3.put("1","jueves");
        lista3.put("2","jueves");
        lista3.put("9","viernes");
        lista3.put("0","viernes");
        
        
        
        
    }
    
    

    @Override
    public void getHoyNoCircula() {
        System.out.println("Hoy no circula los vehiculos con engomado color"+color+"y terminacion"+placa);
    }

    @Override
    public String getByPlaca(String dp ) {
        String di = lista3.get(dp);
        return di;
       
       
      
       
    }

    @Override
    public String getTerminacion(String t) {
       String r = lista2.get(t);
       return r;
       
        
    }

    @Override
    public String getColor(String col) {
        String day = lista.get(col);
        return day;
        
    }
    
    
    
}
<?xml version="1.0" encoding="UTF-8"?>
<project-private xmlns="http://www.netbeans.org/ns/project-private/1">
    <editor-bookmarks xmlns="http://www.netbeans.org/ns/editor-bookmarks/2" lastBookmarkId="0"/>
    <open-files xmlns="http://www.netbeans.org/ns/projectui-open-files/2">
        <group>
            <file>file:/Users/arturohdez/NetBeansProjects/SyFB16/SyFP16/src/EMT/HoyNoC.java</file>
            <file>file:/Users/arturohdez/NetBeansProjects/SyFB16/SyFP16/src/EMT/Hoyno.java</file>
            <file>file:/Users/arturohdez/NetBeansProjects/SyFB16/SyFP16/src/EMT/IHoyno.java</file>
        </group>
    </open-files>
</project-private>

